backend:
  name: git-gateway
  repo: ttngocthao/training_2020
  branch: repair
media_folder: /public/images
public_folder: /images

collections:
  - name: workspage
    label: works page
    folder: page
    create: true
    fields:
      - { name: workTitle, label: Title, widget: string }
      - {
          name: heroImg,
          label: Hero Image,
          widget: image,
          media_library:
            {
              config:
                {
                  media_folder: "/{{media_folder}}/page/{{workTitle}}",
                  public_folder: "/{{public_folder}}/page//{{workTitle}}",
                },
            },
        }
      - {
          name: content,
          label: Page Content,
          widget: list,
          fields:
            [
              {
                name: sectionHeading,
                label: Section Heading,
                widget: string,
                required: false,
              },
              {
                name: sectionParagraphs,
                label: Section Paragraphs,
                widget: list,
                required: false,
                fields:
                  [
                    {
                      name: paragraph,
                      label: paragraph,
                      widget: string,
                      required: false,
                    },
                  ],
              },
              {
                name: sectionImages,
                label: Section Images,
                widget: list,
                required: false,
                fields:
                  [
                    {
                      name: image,
                      label: image,
                      widget: image,
                      required: false,
                      media_library:
                        {
                          config:
                            {
                              media_folder: "/{{media_folder}}/page/{{workTitle}}",
                              public_folder: "/{{public_folder}}/page//{{workTitle}}",
                            },
                        },
                    },
                  ],
              },
              {
                name: sectionLinks,
                label: Section Links,
                widget: list,
                required: false,
                fields:
                  [
                    {
                      name: linkLabel,
                      label: Link Label,
                      widget: string,
                      required: false,
                    },
                    {
                      name: linkUrl,
                      label: Link Url,
                      widget: string,
                      required: false,
                    },
                  ],
              },
            ],
        }
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: shortIntro, label: Introduction, widget: string }
      - {
          name: thumbnailImg,
          label: Thumbnail Image,
          widget: image,
          media_library:
            {
              config:
                {
                  media_folder: "/{{media_folder}}/blog/{{title}}",
                  public_folder: "/{{public_folder}}/blog/{{title}}",
                },
            },
        }
      - {
          name: paragraph,
          label: Paragraph,
          widget: list,
          fields:
            [
              {
                name: paragraphHeading,
                label: Heading,
                widget: string,
                required: false,
              },
              {
                name: paragraphText,
                label: Text,
                widget: string,
                required: false,
              },
              {
                name: paragraphImage,
                label: Image,
                widget: image,
                required: false,
                media_library:
                  {
                    config:
                      {
                        media_folder: "/{{media_folder}}/blog/{{title}}",
                        public_folder: "/{{public_folder}}/blog/{{title}}",
                      },
                  },
              },
              {
                name: paragraphLink,
                label: Link,
                widget: string,
                required: false,
              },
            ],
        }
